### ISSUE TITLE
Connector generator failed caused by meta model not registered

### ISSUE THREAD

**Issue by cgourdin** [occiware/OCCI-Studio#11]
Hello,

When i generate a connector with "new connector java project" wizard from my extension i have this error : 
 
![capture d ecran 2017-07-19 a 08 34 12](https://user-images.githubusercontent.com/17008842/28353704-3a230c70-6c5d-11e7-9929-c7cf90d2b189.png)

Before generating, i use the register command OCCI-Studio-->Register OCCI extension.

It is maybe related to issue #10 .

**Comment by fzalila** [comment]
It is related to the generated metamodel and NOT the OCCI extension. 
So, 

- Select vmware.ecore

- Right-click on vmware.ecore

- Select Register Epackages

**Comment by cgourdin** [comment]
I don't have "Register Epackages" submenu when i right click on file vmware.ecore : 
![capture d ecran 2017-07-19 a 08 45 25](https://user-images.githubusercontent.com/17008842/28354058-a64e8d2e-6c5e-11e7-8493-91677bf65bea.png)

**Comment by fzalila** [comment]
Install the Epsilon plugin via https://www.eclipse.org/epsilon/download/.
We will add it in the required dependencies.

**Comment by cgourdin** [comment]
Ok, plugin installed and connector project is generated :-) Thanks.
