### ISSUE TITLE
Generated connector project is not complete

### ISSUE THREAD

**Issue by cgourdin** [occiware/OCCI-Studio#12]
The generated project doesn't have any resources and mixins base objects.
![capture d ecran 2017-07-19 a 09 19 49](https://user-images.githubusercontent.com/17008842/28355308-b59b8fde-6c63-11e7-875c-f8cfe1078277.png)

My vmware extension use core, infrastructure and crtp extensions.
This extension declare new mixins for infrastructure.

**Comment by fzalila** [comment]
Christophe, can you please confirm the resolution of your issue?
best,
Faiez

**Comment by cgourdin** [comment]
Thanks you it works now. I close this issue.
