### ISSUE TITLE
Connector project generation fail

### ISSUE THREAD

**Issue by cgourdin** [occiware/OCCI-Studio#16]
To generate my connector i have registered before my extension : 
![capture d ecran 2017-08-02 a 17 28 55](https://user-images.githubusercontent.com/17008842/28881338-1a7258b2-77a8-11e7-8d81-c1711101dcec.png)

The operation generate connector fail, it show me a message :
![capture d ecran 2017-08-02 a 16 55 01](https://user-images.githubusercontent.com/17008842/28881412-56321040-77a8-11e7-9c0f-aa5b44ee6fcf.png)

**Comment by cgourdin** [comment]
Strangely, this works if i generate sirius design before.

**Comment by fzalila** [comment]
The wizard said, "The **metamodel** of the OCCI cloudmonitoring extension" and NOT "the OCCI cloudmonitoring extension". 
So, cloudmonitoring**.ecore** -> right-click-> register Epackages.

**Comment by fzalila** [comment]
I will delete this requirement. 
Don't close the issue.

**Comment by cgourdin** [comment]
Ok thank you very much :-)
