### ISSUE TITLE
Code generation with mixins introduce compilation error when applied several times

### ISSUE THREAD

**Issue by MaelAudren** [occiware/OCCI-Studio#19]
After creating my model through the visual interface I clicked on the .occie file and select "Generate EMF tooling"
Then I updated the model then I regenerated the EMF tooling. As a consequence two line are added to my generated source code each time I use the generation.

Those lines are : 		
createEOperation(providerEClass, PROVIDER___APPLIES_CONSTRAINT__DIAGNOSTICCHAIN_MAP_1);
and 
createEOperation(credentialsEClass, CREDENTIALS___APPLIES_CONSTRAINT__DIAGNOSTICCHAIN_MAP_1);

In my model, provider and credentials are mixins and the number goes to 2, 3, etc each time I click on generate.

Removing those lines enable to fix the compilation issue introduced.

**Comment by fzalila** [comment]
You must delete the .ecore and .genmodel before regenerating EMF tooling.

**Comment by MaelAudren** [comment]
@fzalila Thank you this totally solve the issue.

**Comment by fzalila** [comment]
Welcome @MaelAudren ! 
I re-open the issue in order to resolve it completely by deleting automatically the .ecore and .genmodel.
