### ISSUE TITLE
Errors when generating EMF tools (linked to omcri.core extension)

### ISSUE THREAD

**Issue by cgourdin** [occiware/OCCI-Studio#21]
When i generate EMF tools, in the end of the process, i have this error :
<img width="870" alt="capture d ecran 2017-09-29 a 10 32 23" src="https://user-images.githubusercontent.com/17008842/31007851-2ef77ff6-a502-11e7-8d8a-eeb59fecb5a3.png">

**Comment by fzalila** [comment]
This bug was detected previously and I fixed it with e2b614ba841a9500b6eb8d5e4fe70be7b4b034b7 since last week. Please check your OCCI-Studio release.
