### ISSUE TITLE
org.eclipse.cmf.occi.core, classes not found in my projects with OCCI Studio build

### ISSUE THREAD

**Issue by cgourdin** [occiware/OCCI-Studio#22]
Hello, when i open my projects, if i have reference to org.eclipse.cmf.occi.core this cause class not found (MixinBase, Resource etc.).
<img width="789" alt="capture d ecran 2017-09-29 a 10 43 12" src="https://user-images.githubusercontent.com/17008842/31008088-19e94198-a503-11e7-8b68-95e1e39ef446.png">

Important: i dont have this errors if i open my project with a run configuration--< eclipse application --< from occi core projects source.

**Comment by fzalila** [comment]
I haven't this behavior with the last release of OCCI-Studio.
Please check your OCCI-Studio version.
<img width="1006" alt="omcri" src="https://user-images.githubusercontent.com/2330030/31009989-979fe5e6-a509-11e7-8c6e-bdb2070f58c2.png">
