### ISSUE TITLE
Link source & target are the opposite in the metamodel vs in instances

### ISSUE THREAD

**Issue by mdutoo** [occiware/OCCI-Studio#25]
Link source & target are the opposite in the metamodel vs in instances (in sirius diagram as well as XML file) ?!

See OpenShift extension screenshots https://github.com/occiware/occiware-openshift/tree/master/screenshots

**Comment by fzalila** [comment]
The user himself chooses the source and target of his link. An enhancement can be proposed by allowing only the permitted links.

**Comment by fzalila** [comment]
Resolved by c2f93d1e4d41ba70805a4fff352152ee533d1b14 and b8f3ccfe0ad43c989d99d330c8cfd368371cf14d.

**Comment by cgourdin** [comment]
I don't know if its related but when i generate a new EMF tools with links i have errors with invariant constants target and source, is it resolved ?

**Comment by fzalila** [comment]
I recently detect this behavior but it seems to be an OCL bug. It will investigate it again.
