### ISSUE TITLE
Add an attribute "Description" on Category meta model

### ISSUE THREAD

**Issue by cgourdin** [occiware/OCCI-Studio#33]
To allow edition of documentation for categories (kind, mixin etc.) when designing an extension.

This field will be used on documentation generation (textile, latex) and will be rendered with model@runtime on model description output.
To edit description, this feature will use a memo (multi-line editor).

**Comment by philippemerle** [comment]
I agree to add a description attribute to categories in order to document detailed description. The Catefory.tilte attribute is more like a short description.
