### ISSUE TITLE
The label of mixin bases inside resource containers must be in 10 points

### ISSUE THREAD

**Issue by philippemerle** [occiware/OCCI-Studio#36]
Currently, the label of mixin bases inside resource containers are in 10 points but should be in 12 points. The label of mixin bases inside link containers seems to be already in 12 points.

**Comment by fzalila** [comment]
The label of mixin bases inside link containers seems to be already in **12 points**.
https://github.com/occiware/OCCI-Studio/blob/af1fb623bde445ddb1de983741e7fd4917c9bf64/plugins/org.eclipse.cmf.occi.core.design/description/OCCIware.odesign#L816
the label of mixin bases inside resource containers are in **10 points** 
https://github.com/occiware/OCCI-Studio/blob/af1fb623bde445ddb1de983741e7fd4917c9bf64/plugins/org.eclipse.cmf.occi.core.design/description/OCCIware.odesign#L776

I make both in 12 points?

**Comment by philippemerle** [comment]
yes both in 12 points.
I changed the title of the issue and the first comment.
