### ISSUE TITLE
Change the Launcher name for MacOS defined in OCCI-Studio.product

### ISSUE THREAD

**Issue by philippemerle** [occiware/OCCI-Studio#4]
Replace Eclipse by "OCCI Studio"

**Comment by gibello** [comment]
A launcher name with a space character is quite weird (at least on Linux, invoking it looks like "./OCCI\ Studio"). File names with spaces generally work, but their use is uncomfortable.

**Comment by fzalila** [comment]
@philippemerle, @gibello, 
our both issues are resolved with d7278ee40d46c37b4270b28e7a3ff39077c39517 and a1209eb66b1ff4ccfe73f2de00cd5f1edf64842f, respectively.
