### ISSUE TITLE
Automatically register extension when importing project and when loading eclipse workspace

### ISSUE THREAD

**Issue by cgourdin** [occiware/OCCI-Studio#40]
Hello,

I have an issue with all studios, when opening my workspace, i have a lot of extension to register manually (OCCI Studio --> register OCCI extension).
Typically i use import extensions from other extensions projects that are present in the workspace. 
Eclipse give me errors on all imported extension from the same workspace like this box: 
![capture d ecran 2018-01-18 a 15 13 06](https://user-images.githubusercontent.com/17008842/35102095-2fefad4a-fc62-11e7-8ab9-5b82342e431e.png)
 
Is there any way to auto-register all extension (.occie) when loading workspace (or just before loading the extension occie in modeling view) ?

**Comment by philippemerle** [comment]
A proposal discussed with Faiez could be:
1) the user selects a set of projects in the workspace (one, some, all)
2) the user selects a new menu item labelled "Register all OCCI extensions"
3) for each of selected projects P:
     if P is a plugin project (i.e., contains a plugin.xml file) then
       read plugin.xml and register the .occie file declared in this file

Is the proposal address your issue?

**Comment by cgourdin** [comment]
Yes, this feature give an overall register extension fonction and it give more time to concentrate on business code. Thank you !
