### ISSUE TITLE
API Support for retrieving all AttributeStates for an Entity

### ISSUE THREAD

**Issue by kortef** [occiware/OCCI-Studio#43]
Currently an `Entity `has a method `getAttributes() ` which returns all `AttributeState`s that belong to the `Entity` itself. To additionally retrieve all `AttributeState`s that are defined by the `MixinBase`s belonging to the `Entity`, one has to retrieve the `MixinBase`s first and then collect all their `AttributeState`s. 

For convenience, I suggest to add another method for `Entity`, e.g., `getAllAttributes()` that returns a combined list comprising the `AttributeState`s that are part of the `Entity` AND those that are part of its `MixinBase`s.

**Comment by fzalila** [comment]
A method getWholeAttributes (Entity) has been added in OcciHelper.
It allows to retreive the different attributes of an entity as well as its mixinbases ones.
commit d3de2476107c5e84b62ff3f75179e9f441e77aab resolves this issue.
