### ISSUE TITLE
Create extension project, fail to create modeling perspective

### ISSUE THREAD

**Issue by cgourdin** [occiware/OCCI-Studio#7]
As shown here : 
![pb_create_project_extension](https://user-images.githubusercontent.com/17008842/28262670-2ff046d4-6ae4-11e7-8f9b-54e64c351167.png)

I fail to create a modeling view perspective with OCCI-Studio --> new extension project. 
There is no modeling view perspective available in product release (downloaded on GitHub) and no options to create a new modeling project.

**Comment by fzalila** [comment]
I am working to resolve this issue. 
It is due to le lack of such dependencies.
You can momentarily resolve this issue by manually completing the Sirius installation.

**Comment by cgourdin** [comment]
Fixed with oxygen release : 4c902d4

**Comment by fzalila** [comment]
Fixed with 5f718a79a8c837270d1304aa6c9f7b4ddff3a125.
