### ISSUE TITLE
EMF Generate tooling fail on my model .occie

### ISSUE THREAD

**Issue by cgourdin** [occiware/OCCI-Studio#9]
With right click on my .occie file : 
![capture d ecran 2017-07-17 a 17 13 38](https://user-images.githubusercontent.com/17008842/28275329-d56bae44-6b13-11e7-937d-cfaeb80187b1.png)

after click : 
![capture d ecran 2017-07-17 a 17 16 01](https://user-images.githubusercontent.com/17008842/28275347-e1a88812-6b13-11e7-8f7c-e7c7460ec6a0.png)

**Comment by cgourdin** [comment]
This bug has been fixed on commit : 4c902d4

**Comment by fzalila** [comment]
Commits https://github.com/occiware/OCCI-Studio/commit/5c9852425b1666655e873ebd38e6396b866a6cf3 and https://github.com/occiware/OCCI-Studio/commit/517c42a52050cfc72b6d73edf973bfcea3a0fe8d resolve the issue.
